"""add_p7_report_and_report_version_tables

Revision ID: 2658519d48fa
Revises: 9443750a1ff5
Create Date: 2026-09-22 20:48:10.974261

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2658519d48fa'
down_revision: str | None = '9443750a1ff5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), server_default=sa.text("'COLLEGE'"), nullable=False),
    sa.Column('latest_version_no', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latest_updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("scope IN ('COLLEGE','CLASS')", name=op.f('ck_report_ck_report_scope')),
    sa.CheckConstraint('latest_version_no >= 0', name=op.f('ck_report_ck_report_latest_version')),
    sa.CheckConstraint('week_no >= 1', name=op.f('ck_report_ck_report_week')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_report_semester_id_semester'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report')),
    sa.UniqueConstraint('semester_id', 'week_no', 'scope', name='uq_report_sem_week_scope'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_semester_id'), 'report', ['semester_id'], unique=False)
    op.create_table('report_version',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_revision', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('rule_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('template_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('snapshot_file_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('excel_file_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'GENERATING'"), nullable=False),
    sa.Column('attempt_token', sa.String(length=64), nullable=True),
    sa.Column('generated_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('generated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("status IN ('GENERATING','PUBLISHED','FAILED')", name=op.f('ck_report_version_ck_report_version_status')),
    sa.CheckConstraint('source_revision >= 0', name=op.f('ck_report_version_ck_report_version_source_revision')),
    sa.CheckConstraint('version_no >= 1', name=op.f('ck_report_version_ck_report_version_no')),
    sa.ForeignKeyConstraint(['excel_file_id'], ['file_object.id'], name=op.f('fk_report_version_excel_file_id_file_object'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['user_account.id'], name=op.f('fk_report_version_generated_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name=op.f('fk_report_version_report_id_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_file_id'], ['file_object.id'], name=op.f('fk_report_version_snapshot_file_id_file_object'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_version')),
    sa.UniqueConstraint('report_id', 'version_no', name='uq_report_version_report_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_report_version_generated_by'), 'report_version', ['generated_by'], unique=False)
    op.create_index(op.f('ix_report_version_report_id'), 'report_version', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_version_status'), 'report_version', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop_table 会一并移除表上的索引与外键；MySQL 禁止单独 drop 被外键依赖的索引，
    # 故此处不逐个 drop_index（autogenerate 生成的顺序会在 drop_table 前先 drop 索引而报错）。
    op.drop_table('report_version')
    op.drop_table('report')
    # ### end Alembic commands ###
