"""add_p6_objection_and_objection_file_tables

Revision ID: 3089c15c178f
Revises: aab8c1088897
Create Date: 2026-09-22 13:03:27.797271

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3089c15c178f'
down_revision: str | None = 'aab8c1088897'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objection',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('attendance_record_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('base_attendance_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('desired_type', sa.String(length=16), nullable=False),
    sa.Column('initial_status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('initial_reviewed_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('initial_reviewed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('initial_comment', sa.String(length=512), nullable=True),
    sa.Column('final_status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('final_reviewed_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('final_reviewed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('final_comment', sa.String(length=512), nullable=True),
    sa.Column('final_attendance_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("desired_type IN ('NORMAL','LEAVE','LATE','ABSENT')", name=op.f('ck_objection_ck_objection_desired_type')),
    sa.CheckConstraint("final_attendance_type IS NULL OR final_attendance_type IN ('NORMAL','LEAVE','LATE','ABSENT')", name=op.f('ck_objection_ck_objection_final_attendance_type')),
    sa.CheckConstraint("final_status IN ('PENDING','APPROVED','REJECTED')", name=op.f('ck_objection_ck_objection_final_status')),
    sa.CheckConstraint("initial_status IN ('PENDING','PASSED','REJECTED')", name=op.f('ck_objection_ck_objection_initial_status')),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_record.id'], name=op.f('fk_objection_attendance_record_id_attendance_record'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_reviewed_by'], ['user_account.id'], name=op.f('fk_objection_final_reviewed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initial_reviewed_by'], ['user_account.id'], name=op.f('fk_objection_initial_reviewed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_objection_student_id_student'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objection')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_objection_attendance_final_status', 'objection', ['attendance_record_id', 'final_status'], unique=False)
    op.create_index(op.f('ix_objection_attendance_record_id'), 'objection', ['attendance_record_id'], unique=False)
    op.create_index('ix_objection_student_id', 'objection', ['student_id'], unique=False)
    op.create_table('objection_file',
    sa.Column('objection_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('file_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_object.id'], name=op.f('fk_objection_file_file_id_file_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['objection_id'], ['objection.id'], name=op.f('fk_objection_file_objection_id_objection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('objection_id', 'file_id', name=op.f('pk_objection_file')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    # 注：autogenerate 另检出一个与学生 administrative_class_id 相关的历史遗留索引差异，
    # 属 P6 之前的既有漂移，不在本迁移职责内，故此处刻意不纳入；保持 P6 迁移仅新增异议两表。
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL 禁止单独 drop 被外键依赖的索引（err 1553，如 ix_objection_student_id
    # 支撑 fk_objection_student_id_student）；且 drop_table 会随表一并删除其全部索引，
    # 故此处整体 drop_table，不再逐个 drop_index（autogenerate 的逐索引删除在此必失败）。
    op.drop_table('objection_file')
    op.drop_table('objection')
