"""add_p7_report_source_revision_table

Revision ID: 9443750a1ff5
Revises: 3089c15c178f
Create Date: 2026-09-22 18:22:45.786916

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9443750a1ff5'
down_revision: str | None = '3089c15c178f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_source_revision',
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint('revision >= 0', name=op.f('ck_report_source_revision_ck_report_source_revision_nonneg')),
    sa.CheckConstraint('week_no >= 1', name=op.f('ck_report_source_revision_ck_report_source_revision_week')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_report_source_revision_semester_id_semester'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('semester_id', 'week_no', name=op.f('pk_report_source_revision')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_source_revision')
    # ### end Alembic commands ###
