"""add inspection task scheduling deadline domain tables

Revision ID: 949e8719895b
Revises: c6b64769bde3
Create Date: 2026-09-21 15:02:13.841063

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '949e8719895b'
down_revision: str | None = 'c6b64769bde3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_key', sa.String(length=191), nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=16), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('course_schedule_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('teaching_class_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('administrative_class_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('course_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('class_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('classroom_snapshot', sa.String(length=128), nullable=True),
    sa.Column('require_photo_snapshot', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('expected_count_snapshot', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expected_count_current', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('roster_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('canceled_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('canceled_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('cancel_reason', sa.String(length=512), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("inspection_type IN ('COURSE','MORNING_STUDY','EVENING_STUDY')", name=op.f('ck_inspection_task_ck_inspection_task_type')),
    sa.CheckConstraint('end_period >= start_period', name=op.f('ck_inspection_task_ck_inspection_task_period_range')),
    sa.CheckConstraint('expected_count_current >= 0', name=op.f('ck_inspection_task_ck_inspection_task_expected_current')),
    sa.ForeignKeyConstraint(['administrative_class_id'], ['administrative_class.id'], name=op.f('fk_inspection_task_administrative_class_id_administrative_class'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['canceled_by'], ['user_account.id'], name=op.f('fk_inspection_task_canceled_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_schedule_id'], ['course_schedule.id'], name=op.f('fk_inspection_task_course_schedule_id_course_schedule'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_inspection_task_semester_id_semester'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_class.id'], name=op.f('fk_inspection_task_teaching_class_id_teaching_class'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_task')),
    sa.UniqueConstraint('task_key', name=op.f('uq_inspection_task_task_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_inspection_task_inspection_date'), 'inspection_task', ['inspection_date'], unique=False)
    op.create_index(op.f('ix_inspection_task_semester_id'), 'inspection_task', ['semester_id'], unique=False)
    op.create_table('submission_deadline_day',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('deadline_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_submission_deadline_day_ck_submission_deadline_day_version')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_submission_deadline_day_semester_id_semester'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user_account.id'], name=op.f('fk_submission_deadline_day_updated_by_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_deadline_day')),
    sa.UniqueConstraint('semester_id', 'inspection_date', name='uq_submission_deadline_day_sem_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_submission_deadline_day_semester_id'), 'submission_deadline_day', ['semester_id'], unique=False)
    op.create_table('volunteer_day_lock',
    sa.Column('volunteer_user_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_user_id'], ['user_account.id'], name=op.f('fk_volunteer_day_lock_volunteer_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('volunteer_user_id', 'inspection_date', name=op.f('pk_volunteer_day_lock')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('inspection_assignment',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('volunteer_user_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('assign_method', sa.String(length=16), nullable=False),
    sa.Column('assign_reason', sa.String(length=512), nullable=True),
    sa.Column('assigned_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('lock_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("assign_method IN ('AUTO','MANUAL')", name=op.f('ck_inspection_assignment_ck_inspection_assignment_method')),
    sa.ForeignKeyConstraint(['assigned_by'], ['user_account.id'], name=op.f('fk_inspection_assignment_assigned_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_task.id'], name=op.f('fk_inspection_assignment_task_id_inspection_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_user_id'], ['user_account.id'], name=op.f('fk_inspection_assignment_volunteer_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_assignment')),
    sa.UniqueConstraint('task_id', name=op.f('uq_inspection_assignment_task_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_inspection_assignment_volunteer_user_id'), 'inspection_assignment', ['volunteer_user_id'], unique=False)
    op.create_table('submission_deadline_version',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('deadline_day_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('changed_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user_account.id'], name=op.f('fk_submission_deadline_version_changed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deadline_day_id'], ['submission_deadline_day.id'], name=op.f('fk_submission_deadline_version_deadline_day_id_submission_deadline_day'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_deadline_version')),
    sa.UniqueConstraint('deadline_day_id', 'version_no', name='uq_submission_deadline_version_day_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_submission_deadline_version_deadline_day_id'), 'submission_deadline_version', ['deadline_day_id'], unique=False)
    op.create_table('task_roster_member',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('roster_version', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('class_name_snapshot', sa.String(length=128), nullable=True),
    sa.Column('grade_year_snapshot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_task_roster_member_student_id_student'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_task.id'], name=op.f('fk_task_roster_member_task_id_inspection_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_roster_member')),
    sa.UniqueConstraint('task_id', 'roster_version', 'student_id', name='uq_task_roster_member_task_ver_stu'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_task_roster_member_student_id'), 'task_roster_member', ['student_id'], unique=False)
    op.create_index(op.f('ix_task_roster_member_task_id'), 'task_roster_member', ['task_id'], unique=False)
    op.create_table('task_roster_version',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], name=op.f('fk_task_roster_version_created_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_task.id'], name=op.f('fk_task_roster_version_task_id_inspection_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_roster_version')),
    sa.UniqueConstraint('task_id', 'version_no', name='uq_task_roster_version_task_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_task_roster_version_task_id'), 'task_roster_version', ['task_id'], unique=False)
    op.create_table('assignment_change_request',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('request_user_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('processed_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('processed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED')", name=op.f('ck_assignment_change_request_ck_assignment_change_request_status')),
    sa.ForeignKeyConstraint(['assignment_id'], ['inspection_assignment.id'], name=op.f('fk_assignment_change_request_assignment_id_inspection_assignment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['user_account.id'], name=op.f('fk_assignment_change_request_processed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_user_id'], ['user_account.id'], name=op.f('fk_assignment_change_request_request_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment_change_request')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_assignment_change_request_assignment_id'), 'assignment_change_request', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_change_request_request_user_id'), 'assignment_change_request', ['request_user_id'], unique=False)
    op.create_table('task_deadline_assessment',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('deadline_version_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('deadline_at_snapshot', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('assignee_user_id_snapshot', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('evaluated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("result IN ('VALID_SUBMISSION','OVERDUE_UNEXECUTED','CANCELED')", name=op.f('ck_task_deadline_assessment_ck_task_deadline_assessment_result')),
    sa.ForeignKeyConstraint(['assignee_user_id_snapshot'], ['user_account.id'], name=op.f('fk_task_deadline_assessment_assignee_user_id_snapshot_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deadline_version_id'], ['submission_deadline_version.id'], name=op.f('fk_task_deadline_assessment_deadline_version_id_submission_deadline_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_task.id'], name=op.f('fk_task_deadline_assessment_task_id_inspection_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_deadline_assessment')),
    sa.UniqueConstraint('task_id', name=op.f('uq_task_deadline_assessment_task_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # 说明：drop_table 会连同该表上的索引一并删除；MySQL 禁止单独 drop 被
    # 外键依赖的索引（1553），故此处不再逐个 drop_index，仅按依赖逆序 drop_table。
    op.drop_table('task_deadline_assessment')
    op.drop_table('assignment_change_request')
    op.drop_table('task_roster_version')
    op.drop_table('task_roster_member')
    op.drop_table('submission_deadline_version')
    op.drop_table('inspection_assignment')
    op.drop_table('volunteer_day_lock')
    op.drop_table('submission_deadline_day')
    op.drop_table('inspection_task')
    # ### end Alembic commands ###
