"""add P5 submission attendance file tables

Revision ID: aab8c1088897
Revises: 949e8719895b
Create Date: 2026-09-21 22:31:19.668225

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aab8c1088897'
down_revision: str | None = '949e8719895b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_object',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploader_user_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'UPLOADING'"), nullable=False),
    sa.Column('retention_policy_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('purged_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("category IN ('SUBMISSION_PHOTO','OBJECTION_PROOF','IMPORT_FILE','REPORT_FILE','TEMP')", name=op.f('ck_file_object_ck_file_object_category')),
    sa.CheckConstraint("status IN ('UPLOADING','READY','PURGE_PENDING','PURGED','FAILED')", name=op.f('ck_file_object_ck_file_object_status')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_file_object_ck_file_object_size')),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['user_account.id'], name=op.f('fk_file_object_uploader_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_object')),
    sa.UniqueConstraint('object_key', name=op.f('uq_file_object_object_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_file_object_category'), 'file_object', ['category'], unique=False)
    op.create_index(op.f('ix_file_object_status'), 'file_object', ['status'], unique=False)
    op.create_index(op.f('ix_file_object_uploader_user_id'), 'file_object', ['uploader_user_id'], unique=False)
    op.create_table('inspection_submission',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('volunteer_user_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('roster_version', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('deadline_version_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('late_at_submission', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=True),
    sa.Column('review_comment', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("result IN ('NORMAL','ABNORMAL')", name=op.f('ck_inspection_submission_ck_inspection_submission_result')),
    sa.CheckConstraint("review_status IN ('PENDING','APPROVED','REJECTED')", name=op.f('ck_inspection_submission_ck_inspection_submission_review_status')),
    sa.ForeignKeyConstraint(['deadline_version_id'], ['submission_deadline_version.id'], name=op.f('fk_inspection_submission_deadline_version_id_submission_deadline_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_account.id'], name=op.f('fk_inspection_submission_reviewed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_task.id'], name=op.f('fk_inspection_submission_task_id_inspection_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_user_id'], ['user_account.id'], name=op.f('fk_inspection_submission_volunteer_user_id_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_submission')),
    sa.UniqueConstraint('task_id', 'attempt_no', name='uq_inspection_submission_task_attempt'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_inspection_submission_review_status'), 'inspection_submission', ['review_status'], unique=False)
    op.create_index(op.f('ix_inspection_submission_task_id'), 'inspection_submission', ['task_id'], unique=False)
    op.create_index(op.f('ix_inspection_submission_volunteer_user_id'), 'inspection_submission', ['volunteer_user_id'], unique=False)
    op.create_table('submission_abnormal_item',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('attendance_type', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.CheckConstraint("attendance_type IN ('LEAVE','LATE','ABSENT')", name=op.f('ck_submission_abnormal_item_ck_submission_abnormal_item_type')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_submission_abnormal_item_student_id_student'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['inspection_submission.id'], name=op.f('fk_submission_abnormal_item_submission_id_inspection_submission'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_abnormal_item')),
    sa.UniqueConstraint('submission_id', 'student_id', name='uq_submission_abnormal_item_sub_stu'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_submission_abnormal_item_student_id'), 'submission_abnormal_item', ['student_id'], unique=False)
    op.create_index(op.f('ix_submission_abnormal_item_submission_id'), 'submission_abnormal_item', ['submission_id'], unique=False)
    op.create_table('submission_file',
    sa.Column('submission_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('file_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_object.id'], name=op.f('fk_submission_file_file_id_file_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['inspection_submission.id'], name=op.f('fk_submission_file_submission_id_inspection_submission'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id', 'file_id', name=op.f('pk_submission_file')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('attendance_record',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('effective_type', sa.String(length=16), nullable=False),
    sa.Column('current_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('source_submission_item_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("effective_type IN ('NORMAL','LEAVE','LATE','ABSENT')", name=op.f('ck_attendance_record_ck_attendance_record_effective_type')),
    sa.CheckConstraint('current_version >= 1', name=op.f('ck_attendance_record_ck_attendance_record_current_version')),
    sa.ForeignKeyConstraint(['source_submission_item_id'], ['submission_abnormal_item.id'], name=op.f('fk_attendance_record_source_submission_item_id_submission_abnormal_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_attendance_record_student_id_student'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_task.id'], name=op.f('fk_attendance_record_task_id_inspection_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_record')),
    sa.UniqueConstraint('task_id', 'student_id', name='uq_attendance_record_task_stu'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_attendance_record_student_id'), 'attendance_record', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_task_id'), 'attendance_record', ['task_id'], unique=False)
    op.create_table('attendance_record_version',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('attendance_record_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('attendance_type', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("attendance_type IN ('NORMAL','LEAVE','LATE','ABSENT')", name=op.f('ck_attendance_record_version_ck_attendance_record_version_type')),
    sa.CheckConstraint("source_type IN ('SUBMISSION','CORRECTION','OBJECTION_FINAL')", name=op.f('ck_attendance_record_version_ck_attendance_record_version_source_type')),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_record.id'], name=op.f('fk_attendance_record_version_attendance_record_id_attendance_record'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['user_account.id'], name=op.f('fk_attendance_record_version_changed_by_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_record_version')),
    sa.UniqueConstraint('attendance_record_id', 'version_no', name='uq_attendance_record_version_rec_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_attendance_record_version_attendance_record_id'), 'attendance_record_version', ['attendance_record_id'], unique=False)
    # 注：autogenerate 还检测到 student.ix_student_administrative_class_id 的漂移，
    # 属 academic 模块既有表、与本次 P5 提交/考勤/文件表无关，故不纳入本迁移。
    # ### end Alembic commands ###


def downgrade() -> None:
    # 先删子表后删父表；MySQL 禁止 drop 仍被外键依赖的索引，故逐表 drop_table
    # （drop_table 会连同其索引与外键一并原子删除），不单独 drop_index（P4 既有约定）。
    # ### end Alembic commands ###
    op.drop_table('attendance_record_version')
    op.drop_table('attendance_record')
    op.drop_table('submission_file')
    op.drop_table('submission_abnormal_item')
    op.drop_table('inspection_submission')
    op.drop_table('file_object')
