"""academic base data: semester periods classes courses roster schedule calendar volunteer

Revision ID: b12d781b0dc9
Revises: b3f1c7d2a4e5
Create Date: 2026-09-21 08:35:08.915790

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b12d781b0dc9'
down_revision: str | None = 'b3f1c7d2a4e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=64), nullable=False),
    sa.Column('course_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course')),
    sa.UniqueConstraint('course_code', name=op.f('uq_course_course_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('semester',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('first_monday', sa.Date(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED')", name=op.f('ck_semester_ck_semester_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester')),
    sa.UniqueConstraint('code', name=op.f('uq_semester_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('calendar_override',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('override_type', sa.String(length=16), nullable=False),
    sa.Column('source_teaching_weekday', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("override_type IN ('STOP','MAKEUP')", name=op.f('ck_calendar_override_ck_calendar_override_type')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_calendar_override_semester_id_semester'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_override')),
    sa.UniqueConstraint('semester_id', 'date', name='uq_calendar_override_sem_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_calendar_override_semester_id'), 'calendar_override', ['semester_id'], unique=False)
    op.create_table('period_definition',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_period_definition_semester_id_semester'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_period_definition')),
    sa.UniqueConstraint('semester_id', 'period_no', name='uq_period_definition_semester_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_period_definition_semester_id'), 'period_definition', ['semester_id'], unique=False)
    op.create_table('teaching_class',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('course_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('class_code', sa.String(length=64), nullable=True),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_teaching_class_course_id_course'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_teaching_class_semester_id_semester'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaching_class')),
    sa.UniqueConstraint('semester_id', 'course_id', 'class_code', name='uq_teaching_class_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_teaching_class_course_id'), 'teaching_class', ['course_id'], unique=False)
    op.create_index(op.f('ix_teaching_class_semester_id'), 'teaching_class', ['semester_id'], unique=False)
    op.create_table('course_schedule',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('teaching_class_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint('end_period >= start_period', name=op.f('ck_course_schedule_ck_course_schedule_period_range')),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name=op.f('ck_course_schedule_ck_course_schedule_weekday')),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_course_schedule_semester_id_semester'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_class.id'], name=op.f('fk_course_schedule_teaching_class_id_teaching_class'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_schedule')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_course_schedule_semester_id'), 'course_schedule', ['semester_id'], unique=False)
    op.create_index(op.f('ix_course_schedule_teaching_class_id'), 'course_schedule', ['teaching_class_id'], unique=False)
    op.create_table('teaching_class_student',
    sa.Column('teaching_class_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_teaching_class_student_student_id_student'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_class.id'], name=op.f('fk_teaching_class_student_teaching_class_id_teaching_class'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teaching_class_id', 'student_id', name=op.f('pk_teaching_class_student')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('course_schedule_week',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['course_schedule.id'], name=op.f('fk_course_schedule_week_schedule_id_course_schedule'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_schedule_week')),
    sa.UniqueConstraint('schedule_id', 'week_no', name='uq_schedule_week'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_course_schedule_week_schedule_id'), 'course_schedule_week', ['schedule_id'], unique=False)
    op.create_table('volunteer_qualification',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('student_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], name=op.f('fk_volunteer_qualification_created_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_volunteer_qualification_semester_id_semester'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_volunteer_qualification_student_id_student'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteer_qualification')),
    sa.UniqueConstraint('semester_id', 'student_id', name='uq_volunteer_qualification_sem_stu'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_volunteer_qualification_semester_id'), 'volunteer_qualification', ['semester_id'], unique=False)
    op.create_index(op.f('ix_volunteer_qualification_student_id'), 'volunteer_qualification', ['student_id'], unique=False)
    op.add_column('administrative_class', sa.Column('college', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意：不对被外键依赖的命名列索引单独 drop_index（MySQL 会拒绝），
    # drop_table 会连同其索引与约束一并移除；按依赖逆序删子表再删父表。
    op.drop_column('administrative_class', 'college')
    op.drop_table('volunteer_qualification')
    op.drop_table('course_schedule_week')
    op.drop_table('teaching_class_student')
    op.drop_table('course_schedule')
    op.drop_table('teaching_class')
    op.drop_table('period_definition')
    op.drop_table('calendar_override')
    op.drop_table('semester')
    op.drop_table('course')
    # ### end Alembic commands ###
