"""add import_batch table

Revision ID: c6b64769bde3
Revises: b12d781b0dc9
Create Date: 2026-09-21 12:58:41.069173

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6b64769bde3'
down_revision: str | None = 'b12d781b0dc9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PREVIEW', nullable=False),
    sa.Column('semester_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('teaching_class_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mysql'), nullable=False),
    sa.CheckConstraint("status IN ('PREVIEW','CONFIRMED','FAILED','EXPIRED')", name=op.f('ck_import_batch_ck_import_batch_status')),
    sa.CheckConstraint("target IN ('roster','timetable','volunteer')", name=op.f('ck_import_batch_ck_import_batch_target')),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], name=op.f('fk_import_batch_created_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], name=op.f('fk_import_batch_semester_id_semester'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teaching_class_id'], ['teaching_class.id'], name=op.f('fk_import_batch_teaching_class_id_teaching_class'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_batch')
    # ### end Alembic commands ###
